### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by xrotwang** [clld/clld-markdown-plugin#1]
- must work with custom ID prefixes to accomodate clld apps serving aggregated CLDF content such as Dictionaria
- must provide custom rendering per datatype
- must provide a mapping of CLDF components to clld model classes (base classes should suffice, I guess)
- must provide ways to retrieve all referenced objects from db and provide them for rendering - but optionally, if rendering links isn't enough.

**Comment by xrotwang** [comment]
Here's an initial prototypical function from ACD:
```python
def markdown(req, s):
    def repl(ml):
        comp_to_route = {
            'LanguageTable': 'language',
            'Source': 'source',
        }
        if ml.is_cldf_link:
            try:
                ml.url = req.route_url(comp_to_route[ml.component()], id=ml.objid)
            except:
                print(ml.component(), ml)
        return ml

    md = Markdown(extensions=[
        TocExtension(permalink=True),
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables'])
    return md.convert(CLDFMarkdownLink.replace(s, repl)), md
```

**Comment by fmatter** [comment]
How to best accommodate custom models?

**Comment by fmatter** [comment]
I think I've covered your points 2/3/4, as well as my custom model requirement.

Items are retrieved with `DBSession` and the `objid`.
To just link entities, a dict is used in combination with a function:

```
model_map = {
    "LanguageTable": {"route": "language", "model": Language},
    "ExampleTable": {"route": "sentence", "model": Sentence},
    "sources.bib": {"route": "source", "model": Source},
}

def link_entity(req, objid, route, model, decorate=None):
    entity = DBSession.query(model).filter(model.id == objid)[0]
    url = req.route_url(route, id=objid)
    md_str = f"[{entity.name}]({url})"
    if decorate is None:
        return md_str
    else:
        return decorate(md_str)
```

If a table is in `function_map`, a custom function is used.
If a file `clld_own_markdownpy` exists, `custom_model_map` and `custom_function_map` are imported from there.


I am confident that some aspects are hacky, but what can you do...

**Comment by fmatter** [comment]
> must work with custom ID prefixes to accomodate clld apps serving aggregated CLDF content such as Dictionaria

Question: how do these prefixes exactly work? Are CLLD database IDs just prefix + individual CLDF ID?

**Comment by xrotwang** [comment]
After a bit more thinking, I'd say it is the responsibility of the clld app to
- either translate identifiers in the CLDF markdown in sync with re-naming identifiers of CLDF objects upon DB import
- or do the whole CLDF markup rendering at DB import.

In any case, it's only the clld app that knows how to do that, so it shouldn't be pushed down to the plugin.
