### ISSUE TITLE
Handling markdown extensions

### ISSUE THREAD

**Issue by fmatter** [clld/clld-markdown-plugin#5]
I've grown the list of used extensions quite a bit, due to the rather complex document I am getting from pylingdocs:

```
    md = Markdown(
        extensions=[
            TocExtension(permalink=permalink),
            "markdown.extensions.fenced_code",
            "markdown.extensions.md_in_html",
            "markdown.extensions.tables",
            "markdown.extensions.attr_list",
            "markdown.extensions.footnotes",
        ]
    )
```

Right now I was going to add [this subscript extension](https://github.com/jambonrose/markdown_subscript_extension), which got me thinking: 1) the `markdown` function should optionally accept a list of extensions 2) maybe some of the extensions above should not be used by default?

**Comment by xrotwang** [comment]
I reallize that everything I said at https://github.com/clld/clld-markdown-plugin/pull/7#discussion_r1011287128 should go here. So yes, I agree with
- configurable list of extensions
- principled selection of default extensions

**Comment by xrotwang** [comment]
see #7
